#!/bin/sh

set -e

if [ -d /usr/share/lider-cluster-server ]; then
    systemctl stop lider.service
    cp -rf /usr/share/lider-cluster-server /tmp
else

    mkdir -p /usr/share/lider-cluster-server
fi
